install.packages("devtools",lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages("zoo",lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages("knitr",lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages("reshape2",lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages("DT",lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages("htmltools",lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages("rmarkdown",lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('gtable',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('scales',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('Rcpp',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('ggplot2',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('gdtools',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('munsell',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('colorspace',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('plyr',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('lazyeval',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('tibble',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('rlang',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('pillar',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('stringr',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('stringi',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('magrittr',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('htmlwidgets',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('rprojroot',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('backports',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('evaluate',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('yaml',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)
install.packages('highr',lib = '/home/cbrida/DataQualityCheckEuracAlpEnv/Libraries/', dependencies = TRUE)




