---
title: "Data Quality Check Report"
author: "Insitute for Alpine Environment, Eurac Research"
output: html_document
params:
    input_dir:             # dir:  Directory where to put input files.
    output_dir_data:       # dir:  Directory where to save output files
    output_dir_report:     # dir:  Directory where to save output report
    project_dir:           # dir:  Directory of DataQualityCheckEuracAlpEnv package. Inside there are R script, Rmarkdown document and support files.
    data_from_row:         # num:  The row number of the first data row. (How many rows are dedicated to headers? + 1)
    header_row_number:     # num:  The row number of the header names
    datetime_header:       # chr:  The string to use to recognize datetime
    datetime_format:       # chr:  The string to use to recognize datetime. Use only: y -> year, m -> month, d -> day, H -> hour, M -> minute
    datetime_sampling:     # chr:  The string that define the time sampling (in POSIXct format)
    record_header:         # chr:  The string to use to recognize record header
    range_file:            # chr:  The string that indicate the name of range file saved in folder "project_dir/Data/Support_files/Range"
    write_output_files:    # log:  Logical status (TRUE/FALSE) to decide if save output data or not
    write_output_report:   # log:  Logical status (TRUE/FALSE) to decide if save output report or not
    file:                  # chr:  The string that indicate the name of file to process
    start_date:            # date: First date to consider for the analysis. Date before are not considered
---

Report start at **`r Sys.time()`**

### INPUT info:

File selected: **`r  file`**

You have also select these parameters:

+ Data start from row: *`r data_from_row`*
+ The name of column is on row: *`r header_row_number`*
+ The datetime header is: *`r datetime_header`*
+ The record header is: *`r record_header`*
+ The datetime format is: *`r datetime_format`*
+ The sampling interval is: *`r datetime_sampling`*

The folders are:

+ Input data folder: *`r input_dir`*
+ Output data folder: *`r output_dir_data`*
+ Output report folder: *`r output_dir_report`*
+ Project folder: *`r project_dir`*


Range file in *`r range_dir`* is called: *`r range_file`*

You decide:  *`r if(write_output_files == TRUE){paste("to write output file here:", output_dir_data)} else{paste(("to don't write output file"))}`*

And: *`r if(write_output_report == TRUE){paste("to write output report here:", output_dir_report)} else{paste(("to don't write output report"))}`*



*End Report - **`r Sys.time()`** *
