---
title: "DataQualityCheckEuracAlpEnv"
output: github_document
---
# Title: "Readme"

## Introduction

The R package DataQualityCheckEuracAlpEnv provide functions and examples to manage data quality for automatic weather station network. In folder *Main_script* there are some scripts that fix issues of input data and create a clean data output. In folder report there are other script to use to produce a report of data quality check algorithm 

## How to install

```{r,echo=TRUE, eval=FALSE}

install_packages("devtools")
library(devtools)
install_github("bridachristian/DataQualityCheckEuracAlpEnv")
library("DataQualityCheckEuracAlpEnv")

```



## How to use (not completed)

+  Clone the package from https://github.com/bridachristian/DataQualityCheckEuracAlpEnv to use the examples

+  In folder **Main_script** there is:
      + a script for manual quality check. It apply a quality check to a sigle data file.

+  In folder **R** there are some functions developed as specific modules

+  In folder **data** there are subfolders where put input data, support files and a folder where scripts save outputs

<!-- ## [Package Documentetion: Vignette] -->
